# All the libs needed
import numpy as np
import matplotlib
matplotlib.use ('agg')
import matplotlib.pyplot as plt
import treecorr

det = "det_"

gg = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg.read("data/gg_corr_" + det + "all.fits", file_type="FITS")

gg_20 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_20.read("data/gg_corr_" + det + "20.fits", file_type="FITS")

gg_21 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_21.read("data/gg_corr_" + det + "21.fits", file_type="FITS")

gg_22 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_22.read("data/gg_corr_" + det + "22.fits", file_type="FITS")

gg_23 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_23.read("data/gg_corr_" + det + "23.fits", file_type="FITS")

gg_24 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_24.read("data/gg_corr_" + det + "24.fits", file_type="FITS")

gg_25 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_25.read("data/gg_corr_" + det + "25.fits", file_type="FITS")

gg_cross_20 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_cross_20.read("data/gg_cross_" + det + "20.fits", file_type="FITS")

gg_cross_21 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_cross_21.read("data/gg_cross_" + det + "21.fits", file_type="FITS")

gg_cross_22 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_cross_22.read("data/gg_cross_" + det + "22.fits", file_type="FITS")

gg_cross_23 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_cross_23.read("data/gg_cross_" + det + "23.fits", file_type="FITS")

gg_cross_24 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_cross_24.read("data/gg_cross_" + det + "24.fits", file_type="FITS")

gg_cross_25 = treecorr.GGCorrelation(min_sep=1, max_sep=100, nbins=20, sep_units='arcmin', var_method='jackknife')
gg_cross_25.read("data/gg_cross_" + det + "25.fits", file_type="FITS")

print(gg.varxip)

# Plot the xi functions
plt.errorbar(np.exp(gg.meanlogr), gg.xip, yerr=gg.varxip, linestyle="",marker="*", color='black', label = r'Detection full $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg.meanlogr), gg.xim, yerr=gg.varxim, linestyle="",marker=".", color='black', label = r'Detection full $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_full.pdf')
plt.clf()

plt.errorbar(np.exp(gg_20.meanlogr), gg_20.xip, yerr=gg_20.varxip, linestyle="",marker="*", color='navy', label = r'Truth 20 $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_20.meanlogr), gg_20.xim, yerr=gg_20.varxim, linestyle="",marker=".", color='navy', label = r'Truth 20 $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_20.pdf')
plt.clf()

plt.errorbar(np.exp(gg_21.meanlogr), gg_21.xip, yerr=gg_21.varxip, linestyle="",marker="*", color='blue', label = r'Truth 21 $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_21.meanlogr), gg_21.xim, yerr=gg_21.varxim, linestyle="",marker=".", color='blue', label = r'Truth 21 $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_21.pdf')
plt.clf()

plt.errorbar(np.exp(gg_22.meanlogr), gg_22.xip, yerr=gg_22.varxip, linestyle="",marker="*", color='green', label = r'Truth 22 $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_22.meanlogr), gg_22.xim, yerr=gg_22.varxim, linestyle="",marker=".", color='green', label = r'Truth 22 $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_22.pdf')
plt.clf()

plt.errorbar(np.exp(gg_23.meanlogr), gg_23.xip, yerr=gg_23.varxip, linestyle="",marker="*", color='orange', label = r'Truth 23 $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_23.meanlogr), gg_23.xim, yerr=gg_23.varxim, linestyle="",marker=".", color='orange', label = r'Truth 23 $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_23.pdf')
plt.clf()

plt.errorbar(np.exp(gg_24.meanlogr), gg_24.xip, yerr=gg_24.varxip, linestyle="",marker="*", color='red', label = r'Truth 24 $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_24.meanlogr), gg_24.xim, yerr=gg_24.varxim, linestyle="",marker=".", color='red', label = r'Truth 24 $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_24.pdf')
plt.clf()

plt.errorbar(np.exp(gg_25.meanlogr), gg_25.xip, yerr=gg_25.varxip, linestyle="",marker="*", color='crimson', label = r'Truth 25 $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_25.meanlogr), gg_25.xim, yerr=gg_25.varxim, linestyle="",marker=".", color='crimson', label = r'Truth 25 $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_25.pdf')
plt.clf()

plt.errorbar(np.exp(gg_cross_20.meanlogr), gg_cross_20.xip, yerr=gg_cross_20.varxip, linestyle="",marker="*", color='navy', label = r'Truth 20/full $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_cross_20.meanlogr), gg_cross_20.xim, yerr=gg_cross_20.varxim, linestyle="",marker=".", color='navy', label = r'Truth 20/full $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_cross_20.pdf')
plt.clf()

plt.errorbar(np.exp(gg_cross_21.meanlogr), gg_cross_21.xip, yerr=gg_cross_21.varxip, linestyle="",marker="*", color='navy', label = r'Truth 21/full $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_cross_21.meanlogr), gg_cross_21.xim, yerr=gg_cross_21.varxim, linestyle="",marker=".", color='navy', label = r'Truth 21/full $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_cross_21.pdf')
plt.clf()

plt.errorbar(np.exp(gg_cross_22.meanlogr), gg_cross_22.xip, yerr=gg_cross_22.varxip, linestyle="",marker="*", color='navy', label = r'Truth 22/full $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_cross_22.meanlogr), gg_cross_22.xim, yerr=gg_cross_22.varxim, linestyle="",marker=".", color='navy', label = r'Truth 22/full $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_cross_22.pdf')
plt.clf()

plt.errorbar(np.exp(gg_cross_23.meanlogr), gg_cross_23.xip, yerr=gg_cross_23.varxip, linestyle="",marker="*", color='navy', label = r'Truth 23/full $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_cross_23.meanlogr), gg_cross_23.xim, yerr=gg_cross_23.varxim, linestyle="",marker=".", color='navy', label = r'Truth 23/full $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_cross_23.pdf')
plt.clf()

plt.errorbar(np.exp(gg_cross_24.meanlogr), gg_cross_24.xip, yerr=gg_cross_24.varxip, linestyle="",marker="*", color='navy', label = r'Truth 24/full $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_cross_24.meanlogr), gg_cross_24.xim, yerr=gg_cross_24.varxim, linestyle="",marker=".", color='navy', label = r'Truth 24/full $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_cross_24.pdf')
plt.clf()

plt.errorbar(np.exp(gg_cross_25.meanlogr), gg_cross_25.xip, yerr=gg_cross_25.varxip, linestyle="",marker="*", color='navy', label = r'Truth 25/full $\xi_+ (\theta)$')
plt.errorbar(np.exp(gg_cross_25.meanlogr), gg_cross_25.xim, yerr=gg_cross_25.varxim, linestyle="",marker=".", color='navy', label = r'Truth 25/full $\xi_- (\theta)$')
plt.xscale('log')
plt.yscale('log')
plt.ylim(1e-7,1e-3)
plt.xlabel(r'$\theta$ (arcmin)')
plt.ylabel(r'$\xi$')
plt.legend(loc = 'lower left')
plt.title("2pt GG correlation")
plt.title("2-point shear-shear correlation")
plt.savefig('corr_func_threshold_GG_cross_25.pdf')
plt.clf()
